### ISSUE TITLE
Check amount of votes for game modes?

### ISSUE THREAD

**Issue by Snowstormer** [lykoss/lykos#104]
Earlier michagogo wanted to check the votes for game modes, but turns out there isn't a way to do so. This is why I'm opening this issue :P

**Comment by nyuszika7h** [comment]
I've already been suggesting this, thanks for opening an issue. @jacob1 says the current behavior is intentional, but I don't see any reason for it. It should also show who voted for which game mode, how many votes are needed for a majority, etc.

**Comment by jacob1** [comment]
It's not really intentional, I just never bothered to add it. Also, should it say who voted for what? Might be an unnecessary highlight is all :P. If anything I would just keep it simple and show each roleset and how many votes it has. The number needed for a majority is going to be constantly changing too anyway.

**Comment by nyuszika7h** [comment]
Added in 4b07779.
