### ISSUE TITLE
!stats, when not in a game, ignores !notice settings.

### ISSUE THREAD

**Issue by ChiyoOsaka** [lykoss/lykos#108]
This is from ##werewolf
> [08:55:19 P] * ChanServ sets mode: +o Chiyo
> [08:55:49 P] <Chiyo> !stats
> [08:55:49 P] -lykos- Chiyo: 7 players: ...
> [08:55:50 P] -lykos- Chiyo: It is currently ...
> [08:55:53 P] <Chiyo> !notice
> [08:55:53 P] -lykos- The bot will now always NOTICE you.

The bot sent the stats as a notice, ignoring !notice's preferences.

> [08:55:59 P] <Chiyo> !notice
> [08:55:59 P] -lykos- Gameplay interactions will now use PRIVMSG for you.
> [08:56:01 P] <Chiyo> !stats
> [08:56:01 P] -lykos- Chiyo: 7 players: ...
> [08:56:01 P] -lykos- Chiyo: It is currently day. ...

The bot is saying that it will send messages, but again sends a notice.

If the command is sent in a private message, it will reply in a private message.

**Comment by nyuszika7h** [comment]
This is intentional. All private replies to channel messages are sent in a notice. I see no good reason to change this.

**Comment by nyuszika7h** [comment]
The point is that a query window shouldn't unnecessarily be opened (in most clients, and by default, anyway) for an in-channel interaction. We can't integrate this into `!notice` because many people, inckuding myself, want gameplay and other PM interactions to use `PRIVMSG` and in-channel interactions that need a private reply to use `NOTICE`.
