### ISSUE TITLE
Mysterious plague counted as village win

### ISSUE THREAD

**Issue by ilbelkyr** [lykoss/lykos#114]
At the moment, if neither seer nor wolves act, the game is counted as a village win (the wolves all die of a mysterious plague). Notably, the seer (who idled) will still win, and all wolfteam-aligned players will lose even if they had no ability to act.

Someone (@ishanyx?) suggested that seer and wolves are automatically assigned stasis in this case; others suggested the set of roles "essential" for this purpose should be adjusted. Either way, the current approach unfairly penalizes traitors who in fact spent the night yelling at their idling co-wolves to wake up and kill.

**Comment by ishanyx** [comment]
Not sure about stasis but certainly the idle seer shouldn't get a win even if village wins. No one winning might be better, and just have it not log stats at all. This shouldn't happen because of two or three idlers in large games with other roles on both sides, though - maybe only if /all/ or almost all of the night roles are idle.

**Comment by skizzerz** [comment]
I'd be in favor of just removing this "feature" entirely and letting the reaper handle it.

**Comment by Vgr255** [comment]
+1 for getting rid of it entirely

**Comment by nyuszika7h** [comment]
+1 for getting rid of it too.

**Comment by ilbelkyr** [comment]
See #115.
