### ISSUE TITLE
Ideas for new totems (give some ideas!)

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#116]
I've been meaning to add a black/wolf shaman to lykos for a while now, and I've already done the architecture changes that will let us add another shaman with very few code changes. However, to be viable, it would need some totems on its own (that it could share with crazed, probably). Here are the totems I thought of for this (few ones so far, I had more but forgot, this is why I'm opening this issue):

- Deceit totem; the person who has this totem is seen as wolf if they're villager-aligned, and as villager if they're wolf-aligned.

Ideas? I would like 4-5 totems for wolfteam to use, instead or in addition to existing ones (lycanthropy totem could be a lot of fun), but first need to draw out what we want and what we don't want.

**Comment by skizzerz** [comment]
Totems are meant for ephemeral effects that only last as long as the totem does (one day+one night either starting the night they are given or the day after). The timing of when totems kick in greatly impacts the gameplay of the role using them; if all totems take effect the night they are given then the role is more tactically oriented, making decisions based on what is best for the moment. Similarly, totems that act this way should be in general less powerful as there isn't any time for others to react (note the in general there, obviously there are exceptions where it would not make sense to delay a totem but the totem itself is still powerful on its own). If all totems take effect starting in the day, it moves the role to a more strategic one playing for long-term effects and the end game. Totem placement can influence how teams act and coordinate their next moves. Additionally, these totems can be more powerful in general because the knowledge of who has that totem is known and can be factored into risk decisions before acting.

To get to the point of this thread, you need to figure out if you want your wolf shaman to be a tactical role or a strategic role by default, then base the majority of effects on that.

As for totems, I've said it before and I'll say it again, outside of protection/retribution (for hunter or ghost-heavy games), silence, desperation, and maybe the vote altering totems (although I'd be careful with those; if used you will need less overall wolves), none of the existing totems fit for a wolf shaman. Lycanthropy is just way too overpowered if wolf team gets to know and choose who has it (it's essentially a buffed version of alpha wolf with very few ways to counter it).

Deceit sounds good as a day totem (can't make it activate the night it is given because then there would be a race between seer and wolf shaman to see who acts first, which should never happen--the end result of a night action should be the same no matter when it happens that night).

Remover doesn't really sound all that good. If it removes the role permanently then that violates the basic premise of how totems work. If temporary it is no different from silence totem (except for one case which I'll address below).

A totem I can see being nice would be a tactical totem (eg takes effect that night) which makes it so that when given to a wolf, harlot does not die when visiting and gunner does not instantly kill them when shooting (although can headshot as normal). If GA having a chance at dying when guarding a wolf is enabled, GA would not die either. Not sure what to call such a totem, but it is the net effect you'd have from your removal totem if played on a wolf (minus the silence aspect which is already covered elsewhere).

**Comment by Vgr255** [comment]
Two new totem ideas which came up yesterday in -dev:
- "cloaking" totem, if seer or oracle sees the person having that totem the following night, they see them as villager/default role. This is effectively the opposite of a cursed totem
- "swap" totem (unlike the thief role which I've been planning, or the exchange totem), which changes the side of someone, without actually changing their role. This should be temporary, to avoid wolves going against their teammates if there are many left.

**Comment by skizzerz** [comment]
Closing this off, it's been months since last comment and github issues aren't a great collaboration space for discussion-type things. Maybe throw these up on a wiki page instead once you're ready to revisit them.
