### ISSUE TITLE
Customizable debug mode

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#120]
We should do away with verbose mode, and just have normal and debug mode. The latter should be customizable with options such as:

- [ ] Allow fake nicks
- [ ] Allow `!revealroles`
- [ ] Enable reaper (night/day/idle timers, etc.)
- [ ] Enable verbose logging
- [ ] Enable raw logging (all IRC traffic)
- [ ] Disable rate limits

Feel free to edit this list to add more.

**Comment by Vgr255** [comment]
I remember @jacob1 mentioned something about the reaper failing in debug mode. Regardless, +1 for this

**Comment by skizzerz** [comment]
Partially implemented with the following options a long time ago:
- DISABLE_DEBUG_MODE_TIMERS
- DISABLE_DEBUG_MODE_TIME_LORD
- DISABLE_DEBUG_MODE_REAPER
- DISABLE_DEBUG_MODE_STASIS

Those can be tweaked in botconfig to enable/disable those features in debug mode. The remainder of the issue I think should be closed off as WONTFIX -- the point of debug mode is not to run regular games, but to provide tools and utilities useful in debugging and testing the game. In this regard, I view fake nicks, !revealroles, and all other debug mode commands as an absolute must-have. On the flip side, if one desires to run normal games, none of those things should be enabled, and that's what our normal and verbose modes already achieve.

Disabling rate limits in debug mode could be useful, as could enabling debug logging in normal modes, although I have an idea for a new feature that would obviate the need for the latter, while the former I don't think has ever tripped me up. However, I think separate targeted issues should be opened for those things instead of a gigantic all-encompassing issue that stays open forever and a day. Can we create aforementioned issues (if needed) and close this one out?
