### ISSUE TITLE
Add a !replace command to swap out an existing player from the same account

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#129]
If someone joins from an account which another player already joined from, the bot should display a message like this:

```
<moo> !join
-lykos- You have already joined under the nick "cow". If you want to join from this connection instead, use "!replace cow".
<moo> !replace cow
* lykos sets mode ##werewolf [-v+v cow moo]
<@lykos> **moo** has replaced **cow**.
```

(The parts in `**...**` should be bolded.)

To extend the usefulness of this feature, the command should also work when a game has already started, as someone already suggested in `##werewolf-dev` earlier.

This should **not** be allowed for users from the same hosts&mdash;~~unless perhaps they're cloaked (and not a `/session` gateway cloak), but that would be too freenode-specific.~~

Also, the name of the command is up to discussion. It could also be `!swap` or something.

**Comment by ishanyx** [comment]
"This should not be allowed for users from the same hosts—unless perhaps they're cloaked"
If they have the same cloak they're on the same account, or else there's something strange going on that we don't really need to support (eg someone switching between cloaked and non-cloaked accounts on the same connection). I don't think this needs to care about hostnames at all, ever. Account-linked cloaks are redundant here (since we're checking accounts anyway) and any other hostname can potentially be shared by multiple users.

**Comment by nyuszika7h** [comment]
Yeah, you're right.

**Comment by skizzerz** [comment]
I'm not convinced on the usefulness of this; if they are the same person that switched connections or something, NickServ typically can take care of that just fine, and if not there is always !fquit.

I can see the usefulness of blocking multiple joins from the same account (although that check should be disabled in debug mode), but I just don't see the utility of having a !replace command.

Also note that such blocking should really only be accounts-based. There are too many instances where different people could have the same hostmask for blocking hostmasks to be a good idea (thinking of not just freenode here).

**Comment by nyuszika7h** [comment]
I might want continue playing from my phone but **not** ghost my 24/7 WeeChat connection on my server. (I tend to just use SSH, but using an IRC client is less painful and probably conserves the battery better).

**Comment by ishanyx** [comment]
What nyuszika7h said. I sometimes lose power/internet at home and switch to my phone, but there's nothing wrong with my main connection - I just can't ssh to it usefully from my phone. If it's joined to a game that already started I can't do much about it at that point. !fquit would work in join phase but once the game's in progress that's likely to mess up the game.

**Comment by jacob1** [comment]
In that case I would probably /ns release jacob1, although I tried that once and was unable to due to it refusing to run that command (I think that bug is fixed on freenode now).

But still, a !replace command would be much better in this case and I would rather use that than changing my main znc connection into a guest nick
