### ISSUE TITLE
Why is !ping being removed?

### ISSUE THREAD

**Issue by ChiyoOsaka** [lykoss/lykos#137]
I don't recall hearing, or being involved in any discussion about this.

**Comment by MJ94** [comment]
I agree. I am not fond of the !ping removal.

**Comment by skizzerz** [comment]
This has been discussed to death (and then some) on -dev, and was brought up at least once in -ops as well. If you were unaware of it, be more active on -dev or more active in general.

It's happening, deal with it. I posted 5 very good reasons for removing it on -dev yesterday. I'm not at my pc but perhaps someone else can supply the log.

--
Ryan Schmidt

**Comment by jacob1** [comment]
We all agreed in -ops that removing !ping was a good idea. The main reason being the fact that !ping is annoying and often useless. It's rare that you see people join from being pinged, anyone that would have joined has already done !away. The only reason I ever use !ping is for the 30 second wait timer, which has been dealt with separately already. When I use !ping, I don't expect anyone to join really, I just do it for the extra wait time.

Here is an example of how useless !ping can be:
We reset the ping list today, meaning everyone who wasn't /away is now pinged. I joined afterwards, hoping to be part of the huge game I was expecting because of everyone getting pinged. But then ... only one person joined (yn, who thought the ping meant 14 people were joined. After they stopped being confused about why !pingif wasn't working later, they immediately did !away). Out of everyone pinged only one actually noticed and joined. A few people did !away but didn't join. Later we restarted the bot again and another person joined from the ping (michagogo, who actually did !away immediately after the first reset but now decided to join). But basically, out of everyone in the channel, only two actually joined.

But anyway, we haven't had an 8p game since resetting the ping list, and a ton of people have just done !away by now, which shows that the majority of users in the channel don't like being pinged, and only want to be pinged for high player count games using !pingif

**Comment by MJ94** [comment]
Regardless of whether !ping is removed, I am not happy about the ops solely what is best without consulting users. It is this sort of stuff that drives people away (remember the last wolfbot), so I'm worried that if this keeps happening, we will replay what has happened in the last few wolfgame channels.

**Comment by skizzerz** [comment]
The initial idea and majority of discussion took place in -dev, which everyone is welcome to join and participate in. The agreement in -ops is merely a procedural hurdle to get dev decisions applied to ##werewolf itself.

If you want to be consulted on development decisions, join and participate in -dev, it's as simple as that. A very small minority of development decisions will be brought up to discussion in ##werewolf, these are usually ones with a high amount of impact on gameplay and the call is usually for help playtesting the changes in -test rather than during the initial planning.

If you think that this or any other change to the bot is made solely by the ops behind closed doors, you are sorely mistaken.

**Comment by skizzerz** [comment]
Home now, here are the reasons I gave in -dev for why this is happening.

1) Command is worthless as-is, it pings a very limited number of people and the vast majority of players (including a majority of ops) are against it ever being reset. When it is reset, we see a brief surge of activity for maybe a day or two before it goes back down to normal because everyone did !away; in less than half the cases I've looked at did someone actually stick around more than that.
2) Due to said worthlessness, if we did keep it around it would be as opt-in. Suspicions show it will be just as worthless as before, however
3) Keeping around unused code provides a maintenance burden and is subject to hardcore bitrot to the point where it no longer works at all anyway. This is especially problematic when we're in the middle of a large refactoring of the bot internals, less legacy code is a good thing and lets us make the new stuff saner
4) While no exact alternative would exist, data again shows we won't miss out on much. Manual pings can make up for a lot of what this command (didn't) do, and are currently being used already to do just that anyway. For everything else, the loss of functionality will have minimal impact. People will complain for a while and then get over it because it really doesn't matter
4.5) pingif is a really good working alternative already, and player adoption on it is quite good as well (since it is opt-in and yet a large percentage of active players use it)
5) In the event that someone clones lykos and it becomes really popular on some other IRC network, and they really want a !ping, we can evaluate adding it back again, except making design decisions on it that we believe will make the command actually useful and effective rather than reimplementing the old behavior

After the reset, point 1 saw a resurgence of activity for... absolutely zero time whatsoever, which validates that point with more recent data. If you strongly believe ping should still exist, provide valid reasoning why **and back that reasoning up with data from chat logs.** I am **not** going to entertain "what if" scenarios or personal opinions/emotions.

**Comment by zamabe** [comment]
This is great and should happen.

Manual pings serve only to spam. The solution to this *is* actually `!pingif` since it allows a user to specify the conditions under which they can be annoyed. Allowing others to still do manual pings is unnecessary since the bot will ping the user when their threshold is reached; Pinging the victim more, manually, after the bot notifies them of reaching the threshold is still just spamming.

**Comment by zamabe** [comment]
Though I see a problem with `!pingif` being opt-in; namely that it's not publicized/advertised. The only way I knew about it was the deprecation message. Being opt-in with no advertising means no onboarding. There should probably be a message tacked onto the first !pingif generated ping so as to alert new users that it exists.

**Comment by ilbelkyr** [comment]
> Manual pings serve only to spam. The solution to this is actually !pingif since it allows a user to specify the conditions under which they can be annoyed. Allowing others to still do manual pings is unnecessary since the bot will ping the user when their threshold is reached

The idea is not to allow *arbitrary* manual pings; it's to allow pinging people you *know* don't mind, or might be interested in the game for a reason other than size. This has always been allowed anyway.

> Pinging the victim more, manually, after the bot notifies them of reaching the threshold is still just spamming.

If someone doesn't want to be manually pinged, indeed, people shouldn't do that. Many people actually appreciate and *encourage* casual manual pings in certain cases, though.

For example, if I know @ishanyx is around, I'll often ping her for a small game. I do the same for other people who seem like they'd appreciate. If they don't, I won't ping them. Generally, the rule is really "you may manually ping some people who don't mind, but use common sense".

**Comment by zamabe** [comment]
The proper way to do the selective ping based on personal knowledge that you suggest is to do it *yourself* instead of indiscriminately through a manual `!ping`. There's nothing in your reply that this doesn't satisfy.

**Comment by ilbelkyr** [comment]
I think we're talking about different things, to some extent? "Doing it yourself" is what's usually referred to as a "manual ping"; `!ping` isn't normally referred to as "manual ping" to avoid confusion with pinging people yourself directly.

Sorry if I misunderstood you.

**Comment by zamabe** [comment]
I usually say that in the context of the bot. When I say manual ping, I do mean manually causing the bot to pingspam by using the `!ping` trigger. Apologies.

**Comment by Vgr255** [comment]
`!ping` has been removed for some time now, and since there weren't many people complaining, I'm guessing that this is fine. Closing this for now, as I see no real use to keep this open anymore.
