### ISSUE TITLE
Exceptions in threads are not caught by notify_error

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#151]
Like this one:

```
Exception in thread Thread-188:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/home/lykos/lykos/src/wolfgame.py", line 3100, in transition_day
    ps.remove(var.LASTGIVEN.get(shaman))
ValueError: list.remove(x): x not in list
```

**Comment by Vgr255** [comment]
We really need more threading locks. Should the whole transition_day function encapsulate the lock?

**Comment by jacob1** [comment]
This error has nothing to do with threading locks, it was an actual bug that has since been fixed. I haven't seen the need for any more threading locks in a long time.

But anyway ... I remember this being a problem when testing all the new roles a lot. Hopefully easy to catch these exceptions too somehow.

**Comment by nyuszika7h** [comment]
http://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python
