### ISSUE TITLE
!stats sometimes shows dead clone as a live

### ISSUE THREAD

**Issue by eleweek** [lykoss/lykos#167]
We were playing a game where a clone turned wolf was killed the same night by hunter. The next day there was another wolf alive, and the stats was showing this:

  Sep 13 03:37:23 <lykos> Timson: 5 players: godlikesme, auror, Timson, Jake0720, kairi
  Sep 13 03:37:23 <lykos> Timson: It is currently day. There are no wolves, no traitors, 1 oracle, no harlots, 1 shaman, 1 hunter, 1 fool, 1 clone, and no villagers.

The expected output is something like 0-1 wolves are alive, 0-1 clones are alive.

**Comment by jacob1** [comment]
The main issue here is that it implied there were no living wolves when really there are. Somehow we need to figure out a way to show that, and show "0 clones", without revealing what clone turned into.

0-1 on all the wolf roles (wolf, werecrow, cub, alpha wolf, and  / or wolf mystic) would work, or some other method of just saying "1 wolfteam"

**Comment by skizzerz** [comment]
0-1 on all the wolf roles is really messy. In any case, there is no bug here but intended functionality. I asked for this ticket to be opened because I saw a report that "stats shows 1 clone but we know the clone himself died (versus simply turned)." In this case, however, you did not know that the clone died as it would've shown in public that a wolf died -- not the clone.

Adding advanced logic to reflect that it is likely a clone turned into wolfteam due to a game not ending (versus when more wolves die than there are wolves, which is already in the stats calculation) is something on the backburner, but will not be happening in the immediate future. These sorts of cases are quite easy to logic out yourself and as such are very low priority.

**Comment by jacob1** [comment]
We did know that the clone died though, due to it saying there were no wolves left. I still think this is a big enough issue that we should at least attempt to add some kind of fix. If the logic is too complicated then I guess it would be right to close this.

Btw 0-1 probably wouldn't be that ugly, since there are usually not more than like 3 kinds of wolves in a game.
