### ISSUE TITLE
Discussion about using asyncio

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#172]
Please read thorougly before commenting.

So, I have been for a long while contemplating the use of the `asyncio` package as a backend for our IRC library. There are a very large number of advantages to be having from that, and very few downsides. The `asyncio` package is in very active development (faster than Python's bugfix releases rate), and is very robust (unlike our current library). Since we've wanted for a while to upgrade the IRC library (and, in the same movement, provide proper test coverage), that would be the perfect occasion to do so. There are several solutions offered to us should we choose to go this way:

- Require the minimum version of Python to be 3.4;
- Require users to `pip install asyncio`;
- Ship one consistent version of asyncio with the bot;
- Use the stdlib/PyPi version if available, else our own;
- Maintain two different IRC libraries.

The first option is, quite unsurprisingly, out of the question for now. I plan, however, to raise this limit to 3.4 in the future, but that will have to wait. We'll start by increasing to 3.3 (which has a number of small improvements that can increase code readability, although none are really necessary), then we can see about that later (that's out of the scope of this discussion).

The second option is much more appealing to me, but probably less to the end users. We would have to explain in detail how to get pip, and then asyncio. This might turn users away from us, although I do not really fear much about that. We would have to include a clear notice stating how to get those and set it so we can use it properly.

I have mixed feelings towards the third option. On one hand, we ensure all users have the same version of asyncio, and this relegates the burden of keeping the latest version onto us, rather than the end users. On the other hand, this would include additional burden for us, to make sure we use the proper version, and don't break something in the way should we update. Having the same version across all instances would be beneficial, in the end.

I'm not appealed by the fourth option, as we couldn't know for sure the version that's being used; the 3.4.0 version, the latest PyPi release, or the one we shipped? Included for completeness but I'm against it.

As for the fifth option, it's also there for completeness' sake, because really, we shouldn't have two different libraries.

-----------------------------

My final word is that we should work on a good IRC framework based off asyncio, and supply asyncio with lykos (see notes below for some details). Then, we could work on other important stuff like test coverage (which a better IRC library would, by extension, allow us to do). This issue is here for devs and bystanders to talk about this change.

## Notes on providing asyncio

`asyncio` was added to the Python standard library in 3.4, however it is in constant development, and backports up to and including 3.2 are on the Python Package Index. As far as compatibility goes, we're only interested in the public API shared between all versions. We will have the packages named as e.g. `asyncio_32` internally, and then at runtime we would find the proper version to use, then inject the proper module into the `asyncio` key of `sys.modules` for future imports. That is an implementation detail, but I feel it is worth starting to talk about such details (even if they are not the main focus of this discussion) early on, to make sure we all know where we want to go.

-Vgr

**Comment by laneatomic** [comment]
Coming from a Ruby background, and having played around with bots such as Sopel (formerly Willie), I'd be one to say to go the pip route. The only reason I can think of to ship your own version of it is if you are writing something that's tightly coupled to it (which really you shouldn't be), or if you were worried about future updates of asyncio breaking existing functionality.

Additionally, there shouldn't be any issue in bumping up the minimum version of Python to 3.4. Compatibility isn't an issue on the modern major platforms. I've outlined below the minimum OS versions/where Python 3.4 is available from for RHEL/CentOS, Ubuntu/Debian, and FreeBSD. Considering the majority of distributions in use are based on these, other distributions should be similar.

RHEL-Based:
- CentOS/RHEL 7
  - Python 3.4 available as part of core repo
- CentOS/RHEL 6
  - Python 3.4 available from [IUS Community Repo](https://iuscommunity.org/)

Ubuntu/Debian:
- Ubuntu >= 14.04 ships 3.4 out of the box (as /usr/bin/python3)
- Debian since "Jesse" has 3.4 available

FreeBSD:
- Python34 package available from Ports

**Comment by Vgr255** [comment]
I was on a Debian-wheezy (however that's spelled) for a while, and it did not have greater than 3.2.2 - one of our users is also on 3.2. My concern lies there.

**Comment by JeDa** [comment]
Probably they'll need to compile Python 3.4 or get it from some repo which it is available.

**Comment by Vgr255** [comment]
Probably, although I fear that is outside the scope of this discussion.

**Comment by laneatomic** [comment]
Jessie is the latest stable release for Debian. Frankly, since this is probably going to be a major version release of Lykos anyways, perhaps the project should focus on supporting only the latest stable releases of the major distributions? If someone wants to run Lykos on an older distribution (like Wheezy) for some strange reason, they can run Lykos 1.x, with an explicit "This version is EOL" warning.

**Comment by Vgr255** [comment]
I strongly disagree with that opinion. We develop features, and we want them available to everyone running the bot. We have at least one user with 3.2, so as long as they can't use 3.4, we can't, either.

**Comment by Abrackadabra** [comment]
So, the limiting factor in adopting asyncio is the unwillingness of one user to upgrade their python distribution? I think this approach is unhealthy for the future of the project.

**Comment by Vgr255** [comment]
Not unwilligness, unability. Or lack of skill and knowledge. Pick whatever floats your boat. Every user counts, but if we do manage to make them upgrade, yes, I'm willing to go that way.

**Comment by JeDa** [comment]
<s>Otherwise you can download asyncio and modify it so it may work on 3.2 (which I think that will not happen :P)</s>
But we can go at the first option. As Lane said, there may be a 1.0 version which is for older version, and we get working on something like 1.1 or 2.0 working for 3.4.

Vgr, I agree with Lane. It may be bad, yes.

So, there's something left to-do...

Probably make 2 versions (2 repos): the first using oyoyo (3.2-compatible) and another one using asyncio (3.4-compatible).

**Comment by laneatomic** [comment]
It wouldn't have to be 2 repos. Have a 1.x branch/tag and a 2.x branch/tag. And clean up all those old branches that don't need to exist anymore. :facepunch: :boom:

**Comment by Vgr255** [comment]
See point five.

We don't need to modify asyncio to fit our needs, there are already PyPi backports.

**Comment by skizzerz** [comment]
Ubuntu 12.04 and Debian Wheezy are still on Python 3.2. Until those distributions fall out of support (in Debian's case, once Wheezy hits the LTS servicing date of February 2016), I'm quite strongly opposed to upping our minimum version. We still have active bot operators using 3.2, and I'm not sure what their hosting situations are like (e.g. do they own the servers they are hosting on? If not, chances are the OS on them won't be upgraded until they fall out of support).

That being said, as long as the only 3.3 and 3.4 things we require are libraries that can be backported via pip, I don't think it's unreasonable to include them should they make life significantly easier. We should emphatically **not** ship our own version of asyncio or other such libraries. I'm looking into asyncio at the moment to see if it would actually make our lives significantly easier vs coding in all of the "low level" threading stuff ourselves. I suspect it will, but I want it so that any dependencies we might use are backportable.

The largest gain I can see after a cursory glance is the event loops functionality combined with the selectors module, is that part of the asyncio backport?

**Comment by Vgr255** [comment]
You'd have to look at the asyncio backport on PyPi, but I believe they're in (since they're the main attraction). I don't think there are that many differences in the public API, and anyway we could work only with API available in all versions.

As for gain, there are also a number of good IRC frameworks written for asyncio, which we could use.

**Comment by skizzerz** [comment]
I highly doubt any existing IRC framework supports our eventual end-goal of multiple connections to the server as a means of scaling up to larger player counts without having fakelag.

**Comment by jacob1** [comment]
The only option on that list to get asyncio I see that makes sense is using pip. Pip is really easy to use anyway and it shouldn't be a problem to require people to install a library on their own. Bundling the library in with lykos doesn't make sense when libraries are already easy to install.

Anyway I don't know much about asyncio but chances are it will help us in the future (or well, skizzerz said it would) so it sounds good to me.

**Comment by skizzerz** [comment]
Closing this out, consensus seems to be that we'll tentatively use asyncio for the new irc lib; users running versions older than 3.4 will be required to install it via pip.
