### ISSUE TITLE
!p does not support nick completion in PM

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#178]
If you try to use `!p` with a partial nick in PM, such as `!p nyu, it will say "nyu has not played any games".

**Comment by jacob1** [comment]
!p completes role names now, but attempting to complete nicks wouldn't work, mostly because it can be used to check the stats of players who aren't online. If you wanted to check the stats for a person who isn't online who was named "jac", it would attempt to complete to "jacob1" and then you could never check the stats for "jac". You could always send a /notice from the channel if you wanted to tab complete.
