### ISSUE TITLE
Add timestamps to console messages

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#18]
This would be especially useful for tracebacks.

**Comment by nyuszika7h** [comment]
Some things like "RESTARTING" still don't have timestamps as they're printed directly, but at least tracebacks have timestamps now.

**Comment by jacob1** [comment]
https://github.com/lykoss/lykos/commit/653e881b39af386e42aad33be9bf3874b0522c13 should mostly fix this, close the issue?

These are the remaining print statements:
wolfbot.py:    print('Python 3.2 or newer is required to run the bot.')
tools/moduleloader.py:    print("Loading module "+modfile)
oyoyo/client.py:        self.stream_handler = lambda output, level=None: print(output)
oyoyo/client.py:                print("Calling sys.exit()...")

**Comment by Vgr255** [comment]
The stream_handler in oyoyo.client is replaced at runtime by tools.logger, the one you see is a placeholder if oyoyo is ever used for something else. The module loader is going to the forgotten lands of deprecated code in some time, although if you want to add timestamps in the meanwhile go ahead, but it'll get removed anyway. Could modifiy oyoyo.client to take a self.timestamp parameter and use it after I guess.

**Comment by Vgr255** [comment]
This has been added in 26c81c2c03cf1af4ca492a9f971d64d172bfa865

The `"Python 3.2 or newer is required to run the bot."` line does not need a timestamp, as it can only happen right after starting it. And also because Python 2 dislikes the logger's syntax and errors out. The `self.stream_handler` default wasn't modified, since it's not actually used. `"Calling sys.exit()..."` now uses the stream_handler, which has timestamps by itself. The module loader uses the logger now even though it's going away pretty soon.
