### ISSUE TITLE
Remove bcrat and mayor

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#220]
bcrat was a failed experiment that I hoped would make people pay more attention to vote patterns, mayor was just me being a troll. Neither serve any useful purpose in-game.

Alternative to removing mayor would be to make it a real role (villager-aligned), that knows they are mayor. It'll be even more useless than drunk, with their only real power being that they can effectively allow the village to abstain twice instead of just once per game.

**Comment by MJ94** [comment]
I like mayor as it is, to be honest, but I don't like the alternative. So, if it must be changed, I vote to just remove it. Why not keep it?

**Comment by Vgr255** [comment]
I'd nix bureaucrat but keep mayor as-is, really.

**Comment by jacob1** [comment]
Bureaucrat is a role where sometimes you go "oh, someone must be bureaucrat because these votes don't add up", but then it usually wasn't worth it to analyze the previous votes even more to try to figure out who it is. It mostly just confused people when it showed up. I'm fine with it removed. It would take a gamemode designed around it to make sense.

Mayor wouldn't work very well as a role that knows what they are. I do think it is kind of fun when it shows up, it can sometimes give a little hope to a losing team (mostly wolves) if someone that gets lynched turns out the be mayor. I think I added it to lycan game mode because of this? The only issue I can think of is that sometimes people think mayor is a safe role, when really a wolf could be mayor. Also, I think there is a mayor at like 23-24p default. If anything, that mayor could be removed. But you can also remove it entirely if you think it is too trolly.

**Comment by skizzerz** [comment]
OK, so it seems like consensus is remove bureaucrat, but keep mayor as-is? If so, I'll go ahead and do that in a couple of days unless anyone else raises objections.
