### ISSUE TITLE
New role suggestions

### ISSUE THREAD

**Issue by neolito** [lykoss/lykos#240]
- **Witch**, that can revive a chosen dead player but needs a one living sacrifice for the replacement.
- **Ghost**, not a role, but a chance for a lowly villager to be a ghost when lynched, seeking for justice, granting the power to replace a selected player in the game and play their role, making that selected player the dead one.
- **Vampire**, can transform into a bat at night, and i dont know what can his power be. Just a suggestion. Those that i mentioned are roles which i think are good to be added in the game. Election could also be added as the 1st cycle of time. Before the night (the 1st night) there's election day.
- **Mayor**: For the villagers, there should be a mayor, having the power of counting his vote twice or thrice when lynching. A mayor is not a role, just an "added role".
- **Alpha wolf**: For the wolves, there should be an alpha wolf, having the power to attack 2 villagers every night, that wolf should just be the alpha if the pack (group of wolves) survives for 3 nights. Idk. Haha maybe an instant alpha wolf at the 1st night.

Idk if the game will still remain balanced. Just a suggestion of cool roles. :)

**Comment by skizzerz** [comment]
Witch has baggage as a role name due to already being a role in Werewolf. Typically the flavor is that they have a healing potion and a poison potion (each usable only once per game). Each night they are shown who will die that night and has the option of giving them the healing potion (thus saving them). Additionally, they can give someone a poison potion at night to kill them. Your idea doesn't really fit that, so I'm hesitant to call it Witch.

Ghost just sounds not-fun, has no gameplay at all and would leave a very bitter aftertaste in the mouth of the replaced player. Your Witch and Ghost ideas also suffer from the issue that deadchat and !revealroles is a thing -- these dead players may have extra information about who is what based on communicating with other dead players or by checking !revealroles, and that can completely derail a game if they are allowed back in.

No comment on Vampire, as you didn't exactly give any mechanics to it.

Mayor is already a role (a template, rather). The first time they're lynched each game they survive. What you suggest is actually very similar to the removed bureaucrat template (their vote was counted twice). Unlike your suggestion, that was a hidden template so the person did not know they were bureaucrat. It was removed because it was a dud -- even with it in play nobody ever really factored it into their decisions. I'm hesitant to add it back (even as a known template) because I feel it'll still just do absolutely nothing in terms of gameplay. I'm also hesitant on adding a new phase before game start that wastes time for nothing.

Alpha wolf is also already a role with different mechanics than what you suggest, so again you'll need to pick a different name for that.

**Comment by nyuszika7h** [comment]
- **Witch**: I don't like the idea of reviving dead players, they may go AFK after they die. That frequently happens, I know from experience, I do that too sometimes.
- **Ghost**: That already kind of exists as a [https://werewolf.chat/Vengeful_ghost](vengeful ghost), though it's not exactly the same. I don't think we need a similar role.
- **Vampire**: No idea what that is supposed to be.
- **Mayor**: There is already a role called [https://werewolf.chat/Roles#Mayor](mayor), they can stop the village from lynching them once. The role you are talking about used to be present as "bureaucrat", but we removed it in favor of the [https://werewolf.chat/Totem#Influence_totem](influence totem) which shamans can give to make a player's vote count twice.
- **Alpha wolf**: That role [https://werewolf.chat/Alpha_wolf](already exists), but works differently as well.

**Comment by neolito** [comment]
Thank you for your quick response! At least I know that you are interested
for suggestions. Maybe sooner or later I will come up with another idea for
new roles. Hoping to be part of the enhancement of the game :) thank you
again.

On Aug 12, 2016 12:24 AM, "Ryan Schmidt" <notifications@github.com> wrote:
>
> Witch has baggage as a role name due to already being a role in Werewolf.
Typically the flavor is that they have a healing potion and a poison potion
(each usable only once per game). Each night they are shown who will die
that night and has the option of giving them the healing potion (thus
saving them). Additionally, they can give someone a poison potion at night
to kill them. Your idea doesn't really fit that, so I'm hesitant to call it
Witch.
>
> Ghost just sounds not-fun, has no gameplay at all and would leave a very
bitter aftertaste in the mouth of the replaced player. Your Witch and Ghost
ideas also suffer from the issue that deadchat and !revealroles is a thing
-- these dead players may have extra information about who is what based on
communicating with other dead players or by checking !revealroles, and that
can completely derail a game if they are allowed back in.
>
> No comment on Vampire, as you didn't exactly give any mechanics to it.
>
> Mayor is already a role (a template, rather). The first time they're
lynched each game they survive. What you suggest is actually very similar
to the removed bureaucrat template (their vote was counted twice). Unlike
your suggestion, that was a hidden template so the person did not know they
were bureaucrat. It was removed because it was a dud -- even with it in
play nobody ever really factored it into their decisions. I'm hesitant to
add it back (even as a known template) because I feel it'll still just do
absolutely nothing in terms of gameplay. I'm also hesitant on adding a new
phase before game start that wastes time for nothing.
>
> Alpha wolf is also already a role with different mechanics than what you
suggest, so again you'll need to pick a different name for that.

**Comment by skizzerz** [comment]
If you want to discuss this more, we're pretty active in ##werewolf-dev on freenode. Might be easier for the back-and-forth needed to really make a role idea solid rather than doing it on github.

We're always open to new role and gamemode suggestions, but we're also have pretty high standards for getting something like that into the bot, it needs to be conceptually sound and have well-defined mechanics. Most "rough draft" ideas aren't, but that's what the back-and-forth discussion is for.

**Comment by neolito** [comment]
May I ask, you said that there are some of the roles I mentioned that
already exist, what do you mean by "exist"? Are they already in the game?
Because I think I haven't encountered any role like those that I mentioned,
yet. Or did you mean those roles had been in the game but now were removed?
Thanks

**Comment by nyuszika7h** [comment]
See my comment, I linked to the roles on the wiki (except bureaucrat which was removed).

**Comment by neolito** [comment]
Ok, thanks!

**Comment by skizzerz** [comment]
Witch exists as a role in Werewolf in general, although it does not exist on the lykos bot -- many in real life variants of werewolf feature that role, and they all are consistent with each other for how it works. If we were to add it to the bot, I would want it to be consistent with the others as well. Mayor and alpha wolf exist as roles in the lykos bot, the mechanics of them are in the wiki links that @nyuszika7h provided.

**Comment by neolito** [comment]
I have read the wiki. That roles aren't the same as the roles that are in
the werewolf game on telegram. May I know where that game is being played?
Sorry I'm just really confused. I'm really sorry.

On Aug 12, 2016 12:42 AM, "nyuszika7h" <notifications@github.com> wrote:

See my comment, I linked to the roles on the wiki (except bureaucrat which
was removed).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lykoss/lykos/issues/240#issuecomment-239218070>, or mute
the thread

**Comment by neolito** [comment]
I mean where is the game with such roles like vengeful ghost, lycan,
oracle, etc is being played? Because the game I am referring to is the
werewolf game on telegram which has no vengeful ghost, lycan, oracle, and
others. I am just confused and hoping for a reply. Thank you and sorry
again for my confusion.

**Comment by nyuszika7h** [comment]
This game has nothing to do with Telegram, it's on the ##werewolf channel on the freenode IRC network. You are probably in the wrong place.

**Comment by neolito** [comment]
Ok thank you again :)
