### ISSUE TITLE
Dead players sometimes not considered dead

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#256]
Happened in maelstrom. Mayor with desperation totem was lynched, causing totem to fire and killing player A. Player A was assassin targeting player B, and thus caused B to die as well. The mayor was then revealed as mayor, A and B were not devoiced but were also considered dead (could use !revealroles, were not given a role pm at night). At the end of night, they were devoiced and joined to deadchat.

**Comment by jacob1** [comment]
Looked into this, it is a bug with mayor. del_player remembers the list of players to devoice and to join to the deadchat, and tries to do them all at once when the original lynch goes through. But since mayor is never actually lynched, that never happens.

Desperation totem fires in an event, mayor is supposed to fire in an event before that so it never even gets to that point. But mayor hasn't been split yet and the mayor handling actually happens after desperation totem right now. The solution is to split mayor and have the mayor event happen before desperation totem and cancel the lynch.

If I have time soon I can split mayor, it should be incredibly simple and needs to be done to fix this bug anyway.
