### ISSUE TITLE
Using !fflags to grant someone flags doesn't add entries for the grantee to the person/player database tables

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#270]
Using !fflags to grant someone flags doesn't add entries for the grantee to the person/player database tables. In order to give someone flags, we have to warn them or have them complete a game first.

**Comment by jacob1** [comment]
This is fixed in https://github.com/lykoss/lykos/commit/f101c62af8409f235cb5aa4f055915269ff27f4d

Soon we will cherry-pick the commit onto stable, until we figure that out you can either ignore this bug, or you can "git checkout master". Sometime very soon we will modify !fpull to only use stable branches, because the current master branch has several bugs.
