### ISSUE TITLE
Game ends with "no players remaining" if everyone is injured

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#278]
If all remaining players are injured (gunner wound or narcolepsy totem), the game ends with "no players remaining" and nobody wins.

**Comment by skizzerz** [comment]
Intentional design decisions aren't bugs. Now, I do agree that the design decision is a bit stupid when multiple of these effects can stack, and could probably use a change.

I proposed in-chan changing it so that should it drop # of wolves = # of villagers, that day is automatically ended and it moves on to night phase (in other words, force an abstain without using up the once-per-game abstain). Should # of wolves > # of villagers due to multiple simultaneous effects, then day can continue to allow wolves to wagon someone. For ease of implementation, immediately ending day even in the > case may also be merited (as wolves may not be aware they have majority should it come through things such as narc totem).

In any case, there is an info leak going on here: you're stating that the affected people are fullsafe since usually only 1 or 2 simultaneous effects are really possible. If the game ends immediately, that leak doesn't matter anymore. Should the game continue, wolves may have just been completely exposed and no longer able to pull through and win the game despite having a "free day" where none of them got voted. I'm not sure what sort of impact the leak will have, but my initial guess is that it will not actually affect balance one way or the other even though it has the potential to.

**Comment by skizzerz** [comment]
Cleaning up old discussions. Since nothing happened here for the better part of a year, I'm assuming things are good enough as-is. Re-open this issue if necessary.
